services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cognito,dynamodb,apigateway
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack/init-scripts:/etc/localstack/init-scripts"

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  customer-service:
    build: 
      context: ./customer

    container_name: customer-service
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - localstack
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - COGNITO_ENDPOINT=http://localstack:4566
      - SERVERLESS_ACCESS_KEY=AKcGxHPuDOcFQAqkVFdnB4k1m15Pmbw5z2bLICpkeylnl
    entrypoint: ["/bin/sh", "/app/start.sh"]