// Generated by Qodo Gen

import { AvailableCreditUsecase } from "../AvailableCredit";

describe('AvailableCreditUsecase', () => {

  // Returns correct available credit balance for existing customer with valid salary balance
  it('should return salary balance when customer exists', async () => {
    const mockCustomer = { id: 'customer-123' };
    const mockSalaryBalance = { balance: 1000 };

    const customerRepository = {
      getCustomer: jest.fn().mockResolvedValue(mockCustomer),
      createCustomer: jest.fn(),
      updateCustomer: jest.fn(),
      deleteCustomer: jest.fn()
    };

    const salaryBalanceRepository = {
      getSalaryBalance: jest.fn().mockResolvedValue(mockSalaryBalance),
      updateSalaryBalance: jest.fn(),
      createSalaryBalance: jest.fn(),
      deleteSalaryBalance: jest.fn()
    };

    const usecase = new AvailableCreditUsecase(customerRepository, salaryBalanceRepository);

    const result = await usecase.getAvailableCredit('cognito-123');

    expect(customerRepository.getCustomer).toHaveBeenCalledWith('cognito-123');
    expect(salaryBalanceRepository.getSalaryBalance).toHaveBeenCalledWith('customer-123');
    expect(result).toBe(1000);
  });

  // Throws error when customer not found
  it('should throw error when customer not found', async () => {
    const customerRepository = {
      getCustomer: jest.fn().mockResolvedValue(null),
      createCustomer: jest.fn(),
      updateCustomer: jest.fn(),
      deleteCustomer: jest.fn()
    };

    const salaryBalanceRepository = {
      getSalaryBalance: jest.fn(),
      updateSalaryBalance: jest.fn(),
      createSalaryBalance: jest.fn(),
      deleteSalaryBalance: jest.fn()
    };

    const usecase = new AvailableCreditUsecase(customerRepository, salaryBalanceRepository);

    await expect(usecase.getAvailableCredit('cognito-123'))
      .rejects
      .toThrow('Customer not found');

    expect(customerRepository.getCustomer).toHaveBeenCalledWith('cognito-123');
  });
});
