service: customer-service

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 60
  environment:
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    DYNAMODB_TABLE: CustomersTable
    COGNITO_USER_POOL_ID: us-east-1_local_123456
    COGNITO_APP_CLIENT_ID: local_client_789
    DYNAMODB_ENDPOINT: http://dynamodb:8000
    ENDPOINT_COGNITO: http://localstack:4566

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  
custom:
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0

functions:
  Customer:
    handler: src/handler.handler
    timeout: 60
    events:
      - http:
          path: health
          method: get
        
      - http: 
          path: /customer/user/{cognitoId}
          method: get
         
          request:
            parameters:
              paths:
                cognitoId: true
      - http: 
          path: /customer/{customerId}
          method: get
         
          request:
            parameters:
              paths:
                customerId: true
      - http:
          path: /customer/{customerId}/credit
          method: get
          
          request:
            parameters:
              paths:
                customerId: true
      - http:
          path: /customer/{customerId}/shipping
          method: get
          
          request:
            parameters:
              paths:
                customerId: true
      - http:  
          path: /customer
          method: post
    
      - http:  
          path: /customer/{customerId}/shipping
          method: post
          request:
            parameters:
              paths:
                customerId: true
      - http:  
          path: /customer/{customerId}/salary-record
          method: post
          request:
            parameters:
              paths:
                customerId: true
      - http: 
          path: /customer/{customerId}
          method: delete
          request:
            parameters:
              paths:
                customerId: true
     
resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CustomersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CognitoAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - !Sub arn:aws:cognito-idp:us-east-1:000000000000:userpool/${COGNITO_USER_POOL_ID}